# Generated by Django 2.0.4 on 2019-03-21 13:35
from django.db import migrations

default_contacts = [
    {'name': 'e-mail', 'details': 'max@mail.ru'},
    {'name': 'ICQ', 'details': '41011453500451'},
]


def create_default_data(apps, schema_editor):
    """Заполняем таблицы дефолтными данными
    """
    Contact = apps.get_model('core', 'Contact')
    Translation = apps.get_model('core', 'Translation')

    Contact.objects.bulk_create(Contact(priority=i, **item) for i, item in enumerate(default_contacts, start=1))
    Translation.objects.create(name="EN", priority=1, default=True)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_data, reverse),
    ]
