# Generated by Django 2.0.4 on 2019-03-21 13:35
from django.db import migrations

default_contacts = [
    {'name': 'e-mail', 'contact': 'max@mail.ru'},
    {'name': 'ICQ', 'contact': '41011453500451'},
]


def create_default_data(apps, schema_editor):
    """Заполняем таблицы дефолтными данными
    """
    Contact = apps.get_model('core', 'Contact')
    Contact.objects.bulk_create(Contact(**item) for item in default_contacts)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_data, reverse),
    ]
