# Generated by Django 2.0.4 on 2019-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190324_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='count',
            field=models.TextField(default='Count', verbose_name='Count'),
        ),
    ]
