# Generated by Django 2.0.4 on 2019-03-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0002_auto_20190313_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('limit_items', models.ManyToManyField(to='table.LimitItem', verbose_name='Items')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('payment_details', models.TextField(verbose_name='Payment details')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.TypePayment', verbose_name='Payment'),
        ),
    ]
