# Generated by Django 2.0.4 on 2019-03-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0002_auto_20190313_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('total_price', models.FloatField(verbose_name='Total price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_order', models.CharField(max_length=12, verbose_name='Type order')),
                ('tables', models.TextField(verbose_name='Tables')),
                ('term', models.IntegerField(verbose_name='Term')),
                ('start', models.CharField(max_length=8, verbose_name='Start')),
                ('count', models.TextField(verbose_name='Count')),
                ('price', models.FloatField(verbose_name='Price')),
                ('limit_items', models.ManyToManyField(to='table.LimitItem', verbose_name='Items')),
            ],
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('payment_details', models.TextField(verbose_name='Payment details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='order.OrderItem', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.TypePayment', verbose_name='Payment'),
        ),
    ]
