# Generated by Django 2.0.4 on 2019-03-18 07:03
from django.db import migrations

default_payments = [
    {'name': 'PayPal', 'payment_details': 'Some details'},
    {'name': 'Яндекс.Деньги', 'payment_details': '41011453500451'},
    {'name': 'Webmoney', 'payment_details': 'Z323123254533, E123214552123, R43435676755'},
]


def create_default_data(apps, schema_editor):
    """Заполняем таблицы дефолтными данными
    """
    TypePayment = apps.get_model('order', 'TypePayment')
    TypePayment.objects.bulk_create(TypePayment(**item) for item in default_payments)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_data, reverse),
    ]
