# Generated by Django 2.0.4 on 2019-03-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190318_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typepayment',
            name='description',
        ),
    ]
