# Generated by Django 2.0.4 on 2019-02-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Limit',
                'verbose_name_plural': 'Limits',
            },
        ),
        migrations.CreateModel(
            name='LimitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Limit item',
                'verbose_name_plural': 'Limit items',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('limit', models.ManyToManyField(blank=True, to='table.Limit', verbose_name='Limits')),
                ('name_url', models.TextField(blank=True, verbose_name='URL name'))
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.AddField(
            model_name='limititem',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='limit',
            name='item',
            field=models.ManyToManyField(blank=True, to='table.LimitItem', verbose_name='Item'),
        ),
    ]
