# Generated by Django 2.0.4 on 2019-03-13 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('priority', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Limit',
                'verbose_name_plural': 'Limits',
                'ordering': ('table__priority', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='LimitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('price_per_month', models.IntegerField(default=0, verbose_name='Price per month')),
                ('price_per_100k', models.IntegerField(default=0, verbose_name='Price per 100k')),
            ],
            options={
                'verbose_name': 'Limit item',
                'verbose_name_plural': 'Limit items',
            },
        ),
        migrations.CreateModel(
            name='PriceFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_month_discount', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Next month discount as a percentage')),
                ('next_limit_discount', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Next limit discount as a percentage')),
                ('retail_value_added', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retail value added as a percentage')),
                ('next_100k_hands_discount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Next 100k hands discount as a percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('priority', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ('limititem__limit__table__priority', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='StatisticLimitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_count_hands', models.TextField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', verbose_name='Array count hands')),
                ('min_value', models.IntegerField(default=0, verbose_name='Minimum value')),
                ('max_value', models.IntegerField(default=0, verbose_name='Maximum value')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistic Limit Item',
                'verbose_name_plural': 'Statistics Limit Item',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('priority', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name_url', models.TextField(blank=True, verbose_name='URL name')),
                ('limits', models.ManyToManyField(blank=True, to='table.Limit', verbose_name='Limits')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ('priority',),
            },
        ),
        migrations.AddField(
            model_name='limititem',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='limititem',
            name='stat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='table.StatisticLimitItem', verbose_name='Statistics'),
        ),
        migrations.AddField(
            model_name='limit',
            name='items',
            field=models.ManyToManyField(blank=True, to='table.LimitItem', verbose_name='Item'),
        ),
    ]
