# Generated by Django 2.0.4 on 2019-02-06 15:18

from django.db import migrations

default_names_sites = ('POKER STARS', '888 POKER', 'WINNING', 'IPOKER')
default_names_limits = (
    'NL2', 'NL4/5', 'NL10', 'NL16', 'NL20/25', 'NL30', 'NL50', 'NL100', 'NL200', 'NL400/500', 'NL600', 'NL1000'
)


def create_default_limits(apps, schema_editor):
    """Заполняем таблицу дефолтными данными
    """
    Site = apps.get_model('table', 'Site')
    LimitItem = apps.get_model('table', 'LimitItem')
    Limit = apps.get_model('table', 'Limit')

    # создаем сайты
    sites = []
    for site_name in default_names_sites:
        site = Site.objects.create(name=site_name)
        sites.append(site)

    # заполняем дефолтную таблицу, ценник на итем выставляем 10
    for name_limit in default_names_limits:
        limit = Limit.objects.create(name=name_limit)

        limit_items = []
        for site in sites:
            limit_item = LimitItem.objects.create(site=site)
            limit_items.append(limit_item)

        limit.item.add(*limit_items)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('table', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_default_limits, reverse),
    ]
